In [13]:
import tensorflow as tf

In [14]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [15]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [16]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.31186217, -0.58209306, -0.1784255 ,  0.13208215,  0.54626733,
        -0.16032279,  0.49943936, -0.12479922, -0.83454615, -0.37114075]],
      dtype=float32)

In [17]:
tf.nn.softmax(predictions).numpy()

array([[0.13476868, 0.05512508, 0.0825391 , 0.11259305, 0.17036872,
        0.08404689, 0.1625746 , 0.0870862 , 0.04282626, 0.06807138]],
      dtype=float32)

In [18]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [19]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [20]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8569 - loss: 0.4878
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9544 - loss: 0.1505
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9675 - loss: 0.1075
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9720 - loss: 0.0887
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9787 - loss: 0.0674


In [21]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9749 - loss: 0.0850


[0.08501462638378143, 0.9749000072479248]

In [22]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [23]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.18287192e-07, 7.36434336e-09, 1.99361457e-05, 2.52513157e-04,
        1.13111343e-09, 9.10914935e-07, 9.09567560e-13, 9.99691010e-01,
        4.95342761e-07, 3.48478570e-05],
       [1.60401754e-08, 1.94595214e-05, 9.99975681e-01, 3.84819077e-06,
        2.70505563e-17, 9.91036131e-07, 1.79396553e-09, 1.46688014e-14,
        3.05122043e-08, 1.49259497e-13],
       [1.58093590e-05, 9.97935772e-01, 5.45313887e-05, 9.83516475e-06,
        8.99877050e-05, 2.22289345e-05, 9.63442217e-05, 1.34101871e-03,
        4.16354684e-04, 1.81489031e-05],
       [9.99731123e-01, 7.56735119e-09, 2.08965968e-04, 1.14161374e-07,
        3.16288116e-08, 5.56165105e-07, 5.40262363e-06, 2.60584238e-06,
        2.71035105e-07, 5.08931480e-05],
       [5.90742775e-06, 3.95313116e-09, 4.34890671e-06, 1.02307119e-07,
        9.89270806e-01, 6.18102320e-07, 2.35390780e-06, 1.29777633e-04,
        1.02687582e-05, 1.05757769e-02]], dtype=float32)>