In [16]:
import tensorflow as tf

In [17]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

c:\Users\abuba\anaconda3\envs\tf_env\lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.3068897 ,  0.24769384,  0.43882385, -0.26568022, -0.62059927,
         0.2625607 , -0.3819168 ,  0.03246582,  0.6325962 ,  0.41450796]],
      dtype=float32)

In [20]:
tf.nn.softmax(predictions).numpy()

array([[0.06520183, 0.11353046, 0.13744187, 0.06794489, 0.04764501,
        0.11523091, 0.06048894, 0.09154613, 0.16682969, 0.13414015]],
      dtype=float32)

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [22]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.8595 - loss: 0.4860
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9542 - loss: 0.1544
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9677 - loss: 0.1077
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9745 - loss: 0.0844
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9768 - loss: 0.0745


In [24]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9779 - loss: 0.0724


[0.0724424198269844, 0.9779000282287598]

In [25]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.8694913e-06, 1.2738948e-08, 4.7484318e-05, 3.5417845e-04,
        1.3002062e-10, 4.0300321e-08, 4.7734348e-13, 9.9958855e-01,
        3.2817482e-07, 6.5858926e-06],
       [2.2709969e-08, 2.7568138e-05, 9.9995422e-01, 1.7912773e-05,
        8.6037087e-11, 9.7806947e-08, 1.9696133e-08, 1.1884099e-13,
        1.6000091e-07, 1.7009036e-13],
       [3.8914931e-07, 9.9855667e-01, 1.1964603e-04, 2.2060791e-05,
        5.1922520e-06, 3.3495733e-06, 5.6467838e-06, 1.1267161e-03,
        1.5997191e-04, 3.2022038e-07],
       [9.9996889e-01, 4.6336875e-12, 1.4789860e-06, 4.0080860e-07,
        3.3213345e-07, 3.3293327e-07, 2.4003155e-06, 9.7986813e-06,
        5.1728102e-09, 1.6268807e-05],
       [1.8506499e-06, 1.3849055e-09, 2.3389232e-06, 4.8114266e-08,
        9.9768186e-01, 5.2220093e-07, 8.3924451e-06, 3.6494494e-05,
        1.6376543e-07, 2.2683060e-03]], dtype=float32)>